### PR TITLE
Update CKEditor to 4.7.1

### PR DESCRIPTION
**Pull request by Boddlnagg**
This PR updates the underlying CKEditor to version 4.7.1. Functionality should be unchanged (all the plugins that were previously included are still included). Plugins and languages that are now part of the "Full Package" have been added.

The default skin was changed from `moono` to `moono-lisa` in version 4.6, so I included the new default skin in this package. This means that the default value for the `ckeditor.skin` needed to change. Is this enough to make existing installations automatically change the skin to the new value (at least if the value was never changed)? I'm not familiar enough with MODX package development/deployment to know about the details here.

In my MODX installation, this update fixed a longstanding issue that I was never able to track down, where CKEditor would scroll to the top of the document after applying certain changes (e.g. appyling a heading format).

### CODE REVIEW

**Comment by alex-lenk** [comment]
**danyaPostfactum**, When will the changes?

**Comment by danyaPostfactum** [comment]
@alex-lenk I am back now. I'l take care about it in January.
@Boddlnagg thanks

**Comment by alex-lenk** [comment]
Thank you so much. We are all waiting for the update of this plugin, it will eliminate many problems.
Best regards!

**Comment by alex-lenk** [comment]
Даня, подскажи, а как слить данную ветку к себе и собрать пакет? что бы потом установить на сайт

**Comment by Indigo744** [comment]
Any news? Looking forward for an update of CKEditor...

**Comment by danyaPostfactum** [comment]
@Boddlnagg thanks. I have updated to 4.8.0 and cherry-picked "save" fix.

**Pull request closed without merging**
